repos:
  - repo: https://github.com/digo5ds/pygitguard
    rev: 1.0.2
    hooks:
      - id: pygitguard-scan
        name: PyGitGuard Scan
        entry: pygitguard
        language: system
        types: [python]
        stages: [pre-commit]
